config/routes.rb
Rails.application.routes.draw do
  resources :enquiries
  get 'admin', to: 'pages#admin'

  get 'contact', to: 'pages#contact'

  get 'about', to: 'pages#about'

  get 'team', to: 'pages#team'

  get 'faq', to: 'pages#faq'

  get 'customer', to: 'pages#customer'

  get 'thanks', to: 'pages#thanks'

  resources :doctors do
    member do
      get :like
      get :unlike
    end
  end

  resources :doctors
  resources :patients
  devise_for :users, controllers: { registrations: "registrations" }

  root 'home#index'

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  belongs_to :user

  mount_uploader :photo, DoctorPhotoUploader

  extend FriendlyId
  friendly_id :full_name, use: :slugged

  acts_as_taggable

  acts_as_votable

  def full_name
    [title, first_name, last_name, post_nominals].compact.join('')
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy, :like, :unlike]

  def like
    @doctor.liked_by current_user
    redirect_to :back
  end

  def unlike
    @doctor.unliked_by current_user
    redirect_to :back
  end


  # GET /doctors
  # GET /doctors.json
  def index
    if params[:tag]
      @doctors = Doctor.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 4)
    else
      @doctors = Doctor.all.paginate(:page => params[:page], :per_page => 4)
    end
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to doctors_url, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:title, :user_id, :first_name, :last_name, :post_nominals, :bio, :photo, :tag_list)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= simple_form_for(@doctor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :post_nominals %>
    <%= f.input :bio %>
    <%= f.input :photo %>
    <%= f.input :tag_list %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <br>
  <h1>We've got a fully sick doctor for all your needs</h1>
  <br>
  <div class="row">
    <div class="col-md-12">
      <% Doctor.tag_counts_on(:tags).each do |tag| %>
        <%= link_to (tag.name + 's (' + tag.count.to_s + ')' ), doctors_path(tag: tag.name), class: 'btn btn-info btn-sm' %>
      <% end %>
      <%= link_to 'All doctors', doctors_path, class: 'btn btn-primary btn-sm'  %>
    </div>
  </div>

  <div class="row">
    <% @doctors.each do |doctor| %>
      <div class="col-md-3 doctor-view">
        <div class="row">
          <div class="col-md-12 doctor-image">
            <img class="img-responsive doctor-image-file" src="<%= asset_path doctor.photo %>">
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <p><strong><%= doctor.title %> <%= doctor.first_name %> <%= doctor.last_name %>, <%= doctor.post_nominals %></strong></p>
            <div class="doctor-bio"><%= doctor.bio %></div>
            <p>
              <% doctor.tags.each do |tag| %>
                <%= link_to tag.name, doctors_path(tag: tag.name) %>  |
              <% end %>
            </p>
            <p>
                <%= link_to 'Edit', edit_doctor_path(doctor), class: "btn-sm btn-primary" %>
                <%= link_to 'Show', doctor_path(doctor), class: "btn-sm btn-primary" %>
                <%= link_to 'Destroy', doctor, method: :delete, class: "btn-sm btn-danger", data: { confirm: 'Are you sure?' } %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <br>
  <%= will_paginate @doctors, class: "flickr_pagination" %>
  <br>
  <br>
  <br>
</div>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

    <p>
      <strong>Title:</strong>
      <%= @doctor.title %>
    </p>

    <p>
      <strong>First name:</strong>
      <%= @doctor.first_name %>
    </p>

    <p>
      <strong>Last name:</strong>
      <%= @doctor.last_name %>
    </p>

    <p>
      <strong>Post nominals:</strong>
      <%= @doctor.post_nominals %>
    </p>

    <p>
      <strong>Bio:</strong>
      <%= @doctor.bio %>
    </p>

    <p>
      <strong>Photo:</strong>
      <%= @doctor.photo %>
    </p>
    <p>
      <% if current_user.voted_for? @doctor %>
        <%= link_to 'Unlike', unlike_doctor_path, class: 'btn btn-warning btn-sm' %>
      <% else %>
        <%= link_to 'Like', like_doctor_path, class: 'btn btn-success btn-sm' %>
      <% end %>
      Likes: <%= @doctor.find_votes_for.size %>
    </p>

    <%= link_to 'Edit', edit_doctor_path(@doctor) %> |
    <%= link_to 'Back', doctors_path %>
</div>