config/routes.rb
Rails.application.routes.draw do
  resources :enquiries
  get 'admin', to: 'pages#admin'

  get 'contact', to: 'pages#contact'

  get 'about', to: 'pages#about'

  get 'team', to: 'pages#team'

  get 'faq', to: 'pages#faq'

  get 'customer', to: 'pages#customer'

  get 'thanks', to: 'pages#thanks'

  resources :doctors do
    member do
      get :like
      get :unlike
    end
  end

  resources :doctors
  resources :patients
  devise_for :users, controllers: { registrations: "registrations" }

  root 'home#index'

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id="brand" href="/">FullySick</span> </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- If a user is signed in, give them a drop-down, otherwise show a sign-in link -->
      <ul class="nav navbar-nav navbar-left">
        <li><a href="/doctors">Doctors</a></li>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Admin', admin_path %></li>
        <li><%= link_to 'Contact', contact_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% if current_user.patient %>
                <li><%= link_to 'My profile', patient_path(current_user.patient) %></li>
                <% else %>
                <li><%= link_to 'Create profile', new_patient_path(user_type: 'patient') %></li>
              <% end %>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
          <% else %>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
          <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FullySick</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <!-- Optional theme -->
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,600,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  
    <%= yield %>

</body>
</html>